name: Upload APK to Dropbox

on:
  repository_dispatch:
    types: [unity_build_completed]

jobs:
  upload_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download APK from Unity Cloud Build
      run: |
        curl -o DefaultAndroid.apk ${{ github.event.client_payload.apk_url }}

    - name: Upload to Dropbox
      run: |
        python3 upload_to_dropbox.py
      env:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        DROPBOX_DEST_PATH: '/path/to/upload/DefaultAndroid.apk'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
